### ISSUE TITLE
Create a new logo for Cover Letter Generator 

### ISSUE THREAD

**Issue by ZubierAbd** [ZubierAbd/covGen#4]
Hi Looking for a new logo for cover letter generator. Right now it is using the default Angular template logo. Would like to replace it. This could be a good first issue for anyone willing to do it. I am not very design centric so would appreciate the help. :)

**Comment by matteomessmer** [comment]
Hi, I could make a logo. What size should it be?

**Comment by ZubierAbd** [comment]
Hi Matteo, 
If you can, make a logo to replace the favicon with the size 16px by 16px and a larger one which can be 500px by 500px. We can scale it from there if necessary. 
Thanks. Assigning this ticket to you. 
Zubier

**Comment by matteomessmer** [comment]
Ok, I made two logos, if you don't like them feel free to tell me. Otherwise you can choose the one you prefer. Then I made the favicon using https://www.favicon-generator.org/
I make a pull request so you can see them, I put them in two separate folders in /src/assets

**Comment by matteomessmer** [comment]
To add the favicon you need this code:
```
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
```

**Comment by matteomessmer** [comment]
If you accept my pull request could you add the label "hacktoberfest-accepted"?

**Comment by ZubierAbd** [comment]
Thanks Matteo, merged your pull request.
